name: Drinking Coffee Now
favicon: null
layout_spectrum: 0
typography_spectrum: 0.7456
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#bababa'
    - '#070709'
    - '#49444a'
    - '#6f6a70'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
