name: Drinking Coffee Now
favicon: null
layout_spectrum: 0
typography_spectrum: 0.49033
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b0aa9c'
    - '#bfd3da'
    - '#32251d'
    - '#831535'
    - '#d4fdfd'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
