name: Drinking Coffee Now
favicon: null
layout_spectrum: 0.6390311985742301
typography_spectrum: 0.9255895488895476
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3542447732761502
  lightness: 0.15382339130155742
  saturation: 0.643218332901597
  rhythmicContrast: 0.3047408580314368
purpose: []
